//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFdemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public Nullable<int> Kind_id { get; set; }
        public Nullable<int> Author_id { get; set; }
        public string Title { get; set; }
        public string PublishedBy { get; set; }
        public string Abstract { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual KindOfBook KindOfBook { get; set; }
    }
}
